version: "3.7"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Yuri100100
      POSTGRES_DB: acesso
    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init.sql:/init.sql:ro

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/fastapi-app:cached
    environment:
      PYTHONPATH: /fastapi-app
      DATABASE_URL: "postgresql+asyncpg://postgres:Yuri100100@db:5432/acesso"
    depends_on:
      - db
    ports:
      - "8011:8011"
    restart: always

volumes:
  db-data:
