"""security_group_nullable

Revision ID: 154edd35ccc4
Revises: 5e0e10ef26b4
Create Date: 2024-07-26 12:37:14.530033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154edd35ccc4'
down_revision = '5e0e10ef26b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_config', 'security_group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_config', 'security_group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
