"""user_organization

Revision ID: 1f39d0df0445
Revises: 90a309736ed6
Create Date: 2024-07-24 16:17:01.093564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f39d0df0445'
down_revision = '90a309736ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_organization',
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('organization_uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid', 'organization_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_organization')
    # ### end Alembic commands ###
