"""subscription

Revision ID: 5e0e10ef26b4
Revises: 370fad443d84
Create Date: 2024-07-24 18:28:58.643218

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5e0e10ef26b4"
down_revision = "370fad443d84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voucher",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IN_USE", "ACTIVE", "INACTIVE", name="voucherstatus"),
            nullable=False,
        ),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_voucher_code"), "voucher", ["code"], unique=True)
    op.create_index(op.f("ix_voucher_uuid"), "voucher", ["uuid"], unique=True)
    op.create_table(
        "subscription",
        sa.Column("service_plan_uuid", sa.Uuid(), nullable=False),
        sa.Column("organization_uuid", sa.Uuid(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_uuid"],
            ["organization.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["service_plan_uuid"],
            ["service_plan.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_subscription_uuid"), "subscription", ["uuid"], unique=True)
    op.create_table(
        "payment",
        sa.Column("method", sa.Enum("VOUCHER", name="paymentmethod"), nullable=False),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column(
            "status", sa.Enum("OPEN", "DONE", name="paymentstatus"), nullable=False
        ),
        sa.Column("subscription_uuid", sa.Uuid(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_uuid"],
            ["subscription.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("subscription_uuid"),
    )
    op.create_index(op.f("ix_payment_uuid"), "payment", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_uuid"), table_name="payment")
    op.drop_table("payment")
    op.drop_index(op.f("ix_subscription_uuid"), table_name="subscription")
    op.drop_table("subscription")
    op.drop_index(op.f("ix_voucher_uuid"), table_name="voucher")
    op.drop_index(op.f("ix_voucher_code"), table_name="voucher")
    op.drop_table("voucher")
    op.execute("DROP TYPE voucherstatus;")
    op.execute("DROP TYPE paymentmethod;")
    op.execute("DROP TYPE paymentstatus;")
    # ### end Alembic commands ###
