"""terms_of_use

Revision ID: b2af58604440
Revises: db17d6fb8c71
Create Date: 2024-07-24 11:53:10.156043

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b2af58604440"
down_revision = "db17d6fb8c71"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "terms_of_use",
        sa.Column("agreement", sa.Boolean(), nullable=False),
        sa.Column("user_profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_profile_uuid"],
            ["user_profile.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_profile_uuid"),
    )
    op.create_index(op.f("ix_terms_of_use_uuid"), "terms_of_use", ["uuid"], unique=True)
    op.create_table(
        "tou_version",
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("document_uri", sa.String(), nullable=False),
        sa.Column("tou_uuid", sa.Uuid(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tou_uuid"],
            ["terms_of_use.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_tou_version_uuid"), "tou_version", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tou_version_uuid"), table_name="tou_version")
    op.drop_table("tou_version")
    op.drop_index(op.f("ix_terms_of_use_uuid"), table_name="terms_of_use")
    op.drop_table("terms_of_use")
    # ### end Alembic commands ###
