"""user

Revision ID: db17d6fb8c71
Revises: 
Create Date: 2024-07-24 11:08:39.111806

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "db17d6fb8c71"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ## User Table
    op.create_table(
        "user",
        sa.Column("email", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "ADMINISTRATOR",
                "OWNER",
                "OPERATOR_WRITE",
                "OPERATOR_READ",
                name="userrole",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("INVITED", "ACTIVE", "INACTIVE", name="userstatus"),
            nullable=False,
        ),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_uuid"), "user", ["uuid"], unique=True)

    ## User Profile Table
    op.create_table(
        "user_profile",
        sa.Column("user_uuid", sa.Uuid(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_uuid"),
    )
    op.create_index(op.f("ix_user_profile_uuid"), "user_profile", ["uuid"], unique=True)

    ## User Preferences Table
    op.create_table(
        "user_preferences",
        sa.Column("language", sa.String(length=14), nullable=False),
        sa.Column("notification", sa.Boolean(), nullable=False),
        sa.Column("user_profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_profile_uuid"],
            ["user_profile.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_profile_uuid"),
    )
    op.create_index(
        op.f("ix_user_preferences_uuid"), "user_preferences", ["uuid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_preferences_uuid"), table_name="user_preferences")
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_user_profile_uuid"), table_name="user_profile")
    op.drop_table("user_profile")
    op.drop_index(op.f("ix_user_uuid"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.execute("DROP TYPE userrole;")
    op.execute("DROP TYPE userstatus;")
    # ### end Alembic commands ###
